@startuml
skinparam defaultFontName Ubuntu

Account o-right- Currency
Transaction o-- Currency
Transaction o-- "1" Category
Transaction o-- "n" Tag

Transaction <|-right- DepositTx
Transaction <|-up- WithdrawalTx

Transaction "n" o--- "1" Account: src

Person *-up- "n" Account
Person *-right-- "n" Category
Person *-- "n" Tag

@enduml
